CREATE TABLE T_FIN_TRANSFER
(
    id                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount                 NUMBER(10, 2) NOT NULL,
    "DATE"                 DATE                                NOT NULL,
    description            VARCHAR(255)                        NOT NULL,
    observation            CLOB,
    created_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    origin_account_id      NUMBER                              NOT NULL,
    destination_account_id NUMBER                              NOT NULL,

    CONSTRAINT FK_ORIGIN_ACCOUNT FOREIGN KEY (origin_account_id) REFERENCES T_FIN_ACCOUNT (ID),
    CONSTRAINT FK_DESTINATION_ACCOUNT FOREIGN KEY (destination_account_id) REFERENCES T_FIN_ACCOUNT (ID)
)