INSERT INTO T_FIN_EXPENSE_CATEGORY (name, type) VALUES ('Lazer', 'NON_ESSENTIAL');
INSERT INTO T_FIN_EXPENSE_CATEGORY (name, type) VALUES ('Alimentação', 'ESSENTIAL');
INSERT INTO T_FIN_EXPENSE_CATEGORY (name, type) VALUES ('Moradia', 'ESSENTIAL');
INSERT INTO T_FIN_EXPENSE_CATEGORY (name, type) VALUES ('Saúde', 'ESSENTIAL');